language: cpp

os: linux
dist: trusty
sudo: required

cache:
   directories:
     - $HOME/deps

addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       - g++-4.9
       - libssl-dev
       - yasm
       - libgmp-dev
       - libgflags-dev
       - libsnappy-dev
       - zlib1g-dev
       - libbz2-dev
       - liblz4-dev
       - autoconf
       - libtool
env:
  global:
    - ENABLE_COVERAGE=Off
    - BUILD_TYPE=Debug

env:
- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"
  - INSTALL_DIR=$HOME/deps
  - CPATH=$CPATH:$INSTALL_DIR/include
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INSTALL_DIR/lib
  - PATH=$PATH:$INSTALL_DIR/bin
  - echo $CPATH
  - echo $LD_LIBRARY_PATH
  - echo $PATH
  - ./ci/install_crypto_tk_deps.sh
  - ./ci/install_grpc.sh
  - ./ci/install_rocksdb.sh


script:
  - ./ci/build.sh